### ISSUE TITLE
error while setup in laravel5.2

### ISSUE THREAD

**Issue by buddharaj** [Braunson/fatsecret-laravel#3]
Call to undefined method [package]
ServiceProvider->__call('package', array('braunson/fat-secret')) in FatSecretServiceProvider.php line 21

I have installed "braunson/fatsecret-laravel": "^5.0"
do reply soon

**Comment by haakym** [comment]
I did this 

```php
public function boot()
{
	// $this->package('braunson/fat-secret');
	$this->register();
}
```

and it seems to be working, though I'm not sure if it's just because the `$this->package()` method is commented out, was purely playing around to get it working.

Followed the set up in the readme and in my `routes/web.php` file if I did something like this:

```php
dd(FatSecret::searchIngredients('coke'));
```

I'll get a response with query results.
